# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ikaroruan/Documents/Repositories/HODT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ikaroruan/Documents/Repositories/HODT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ikaroruan/Documents/Repositories/HODT/CMakeFiles /home/ikaroruan/Documents/Repositories/HODT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ikaroruan/Documents/Repositories/HODT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Vertex

# Build rule for target.
Vertex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Vertex
.PHONY : Vertex

# fast build rule for target.
Vertex/fast:
	$(MAKE) -f CMakeFiles/Vertex.dir/build.make CMakeFiles/Vertex.dir/build
.PHONY : Vertex/fast

#=============================================================================
# Target rules for targets named Delaunay_triangulation

# Build rule for target.
Delaunay_triangulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Delaunay_triangulation
.PHONY : Delaunay_triangulation

# fast build rule for target.
Delaunay_triangulation/fast:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation.dir/build.make CMakeFiles/Delaunay_triangulation.dir/build
.PHONY : Delaunay_triangulation/fast

#=============================================================================
# Target rules for targets named Face

# Build rule for target.
Face: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Face
.PHONY : Face

# fast build rule for target.
Face/fast:
	$(MAKE) -f CMakeFiles/Face.dir/build.make CMakeFiles/Face.dir/build
.PHONY : Face/fast

#=============================================================================
# Target rules for targets named Point

# Build rule for target.
Point: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Point
.PHONY : Point

# fast build rule for target.
Point/fast:
	$(MAKE) -f CMakeFiles/Point.dir/build.make CMakeFiles/Point.dir/build
.PHONY : Point/fast

#=============================================================================
# Target rules for targets named triangulate

# Build rule for target.
triangulate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangulate
.PHONY : triangulate

# fast build rule for target.
triangulate/fast:
	$(MAKE) -f CMakeFiles/triangulate.dir/build.make CMakeFiles/triangulate.dir/build
.PHONY : triangulate/fast

#=============================================================================
# Target rules for targets named Point_with_info

# Build rule for target.
Point_with_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Point_with_info
.PHONY : Point_with_info

# fast build rule for target.
Point_with_info/fast:
	$(MAKE) -f CMakeFiles/Point_with_info.dir/build.make CMakeFiles/Point_with_info.dir/build
.PHONY : Point_with_info/fast

#=============================================================================
# Target rules for targets named HODT

# Build rule for target.
HODT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HODT
.PHONY : HODT

# fast build rule for target.
HODT/fast:
	$(MAKE) -f CMakeFiles/HODT.dir/build.make CMakeFiles/HODT.dir/build
.PHONY : HODT/fast

#=============================================================================
# Target rules for targets named Triangulation

# Build rule for target.
Triangulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Triangulation
.PHONY : Triangulation

# fast build rule for target.
Triangulation/fast:
	$(MAKE) -f CMakeFiles/Triangulation.dir/build.make CMakeFiles/Triangulation.dir/build
.PHONY : Triangulation/fast

#=============================================================================
# Target rules for targets named Face_circulator

# Build rule for target.
Face_circulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Face_circulator
.PHONY : Face_circulator

# fast build rule for target.
Face_circulator/fast:
	$(MAKE) -f CMakeFiles/Face_circulator.dir/build.make CMakeFiles/Face_circulator.dir/build
.PHONY : Face_circulator/fast

#=============================================================================
# Target rules for targets named predicates

# Build rule for target.
predicates: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predicates
.PHONY : predicates

# fast build rule for target.
predicates/fast:
	$(MAKE) -f CMakeFiles/predicates.dir/build.make CMakeFiles/predicates.dir/build
.PHONY : predicates/fast

Delaunay_triangulation.o: Delaunay_triangulation.cpp.o

.PHONY : Delaunay_triangulation.o

# target to build an object file
Delaunay_triangulation.cpp.o:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation.dir/build.make CMakeFiles/Delaunay_triangulation.dir/Delaunay_triangulation.cpp.o
.PHONY : Delaunay_triangulation.cpp.o

Delaunay_triangulation.i: Delaunay_triangulation.cpp.i

.PHONY : Delaunay_triangulation.i

# target to preprocess a source file
Delaunay_triangulation.cpp.i:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation.dir/build.make CMakeFiles/Delaunay_triangulation.dir/Delaunay_triangulation.cpp.i
.PHONY : Delaunay_triangulation.cpp.i

Delaunay_triangulation.s: Delaunay_triangulation.cpp.s

.PHONY : Delaunay_triangulation.s

# target to generate assembly for a file
Delaunay_triangulation.cpp.s:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation.dir/build.make CMakeFiles/Delaunay_triangulation.dir/Delaunay_triangulation.cpp.s
.PHONY : Delaunay_triangulation.cpp.s

Face.o: Face.cpp.o

.PHONY : Face.o

# target to build an object file
Face.cpp.o:
	$(MAKE) -f CMakeFiles/Face.dir/build.make CMakeFiles/Face.dir/Face.cpp.o
.PHONY : Face.cpp.o

Face.i: Face.cpp.i

.PHONY : Face.i

# target to preprocess a source file
Face.cpp.i:
	$(MAKE) -f CMakeFiles/Face.dir/build.make CMakeFiles/Face.dir/Face.cpp.i
.PHONY : Face.cpp.i

Face.s: Face.cpp.s

.PHONY : Face.s

# target to generate assembly for a file
Face.cpp.s:
	$(MAKE) -f CMakeFiles/Face.dir/build.make CMakeFiles/Face.dir/Face.cpp.s
.PHONY : Face.cpp.s

Face_circulator.o: Face_circulator.cpp.o

.PHONY : Face_circulator.o

# target to build an object file
Face_circulator.cpp.o:
	$(MAKE) -f CMakeFiles/Face_circulator.dir/build.make CMakeFiles/Face_circulator.dir/Face_circulator.cpp.o
.PHONY : Face_circulator.cpp.o

Face_circulator.i: Face_circulator.cpp.i

.PHONY : Face_circulator.i

# target to preprocess a source file
Face_circulator.cpp.i:
	$(MAKE) -f CMakeFiles/Face_circulator.dir/build.make CMakeFiles/Face_circulator.dir/Face_circulator.cpp.i
.PHONY : Face_circulator.cpp.i

Face_circulator.s: Face_circulator.cpp.s

.PHONY : Face_circulator.s

# target to generate assembly for a file
Face_circulator.cpp.s:
	$(MAKE) -f CMakeFiles/Face_circulator.dir/build.make CMakeFiles/Face_circulator.dir/Face_circulator.cpp.s
.PHONY : Face_circulator.cpp.s

HODT.o: HODT.cpp.o

.PHONY : HODT.o

# target to build an object file
HODT.cpp.o:
	$(MAKE) -f CMakeFiles/HODT.dir/build.make CMakeFiles/HODT.dir/HODT.cpp.o
.PHONY : HODT.cpp.o

HODT.i: HODT.cpp.i

.PHONY : HODT.i

# target to preprocess a source file
HODT.cpp.i:
	$(MAKE) -f CMakeFiles/HODT.dir/build.make CMakeFiles/HODT.dir/HODT.cpp.i
.PHONY : HODT.cpp.i

HODT.s: HODT.cpp.s

.PHONY : HODT.s

# target to generate assembly for a file
HODT.cpp.s:
	$(MAKE) -f CMakeFiles/HODT.dir/build.make CMakeFiles/HODT.dir/HODT.cpp.s
.PHONY : HODT.cpp.s

Point.o: Point.cpp.o

.PHONY : Point.o

# target to build an object file
Point.cpp.o:
	$(MAKE) -f CMakeFiles/Point.dir/build.make CMakeFiles/Point.dir/Point.cpp.o
.PHONY : Point.cpp.o

Point.i: Point.cpp.i

.PHONY : Point.i

# target to preprocess a source file
Point.cpp.i:
	$(MAKE) -f CMakeFiles/Point.dir/build.make CMakeFiles/Point.dir/Point.cpp.i
.PHONY : Point.cpp.i

Point.s: Point.cpp.s

.PHONY : Point.s

# target to generate assembly for a file
Point.cpp.s:
	$(MAKE) -f CMakeFiles/Point.dir/build.make CMakeFiles/Point.dir/Point.cpp.s
.PHONY : Point.cpp.s

Point_with_info.o: Point_with_info.cpp.o

.PHONY : Point_with_info.o

# target to build an object file
Point_with_info.cpp.o:
	$(MAKE) -f CMakeFiles/Point_with_info.dir/build.make CMakeFiles/Point_with_info.dir/Point_with_info.cpp.o
.PHONY : Point_with_info.cpp.o

Point_with_info.i: Point_with_info.cpp.i

.PHONY : Point_with_info.i

# target to preprocess a source file
Point_with_info.cpp.i:
	$(MAKE) -f CMakeFiles/Point_with_info.dir/build.make CMakeFiles/Point_with_info.dir/Point_with_info.cpp.i
.PHONY : Point_with_info.cpp.i

Point_with_info.s: Point_with_info.cpp.s

.PHONY : Point_with_info.s

# target to generate assembly for a file
Point_with_info.cpp.s:
	$(MAKE) -f CMakeFiles/Point_with_info.dir/build.make CMakeFiles/Point_with_info.dir/Point_with_info.cpp.s
.PHONY : Point_with_info.cpp.s

Triangulation.o: Triangulation.cpp.o

.PHONY : Triangulation.o

# target to build an object file
Triangulation.cpp.o:
	$(MAKE) -f CMakeFiles/Triangulation.dir/build.make CMakeFiles/Triangulation.dir/Triangulation.cpp.o
.PHONY : Triangulation.cpp.o

Triangulation.i: Triangulation.cpp.i

.PHONY : Triangulation.i

# target to preprocess a source file
Triangulation.cpp.i:
	$(MAKE) -f CMakeFiles/Triangulation.dir/build.make CMakeFiles/Triangulation.dir/Triangulation.cpp.i
.PHONY : Triangulation.cpp.i

Triangulation.s: Triangulation.cpp.s

.PHONY : Triangulation.s

# target to generate assembly for a file
Triangulation.cpp.s:
	$(MAKE) -f CMakeFiles/Triangulation.dir/build.make CMakeFiles/Triangulation.dir/Triangulation.cpp.s
.PHONY : Triangulation.cpp.s

Vertex.o: Vertex.cpp.o

.PHONY : Vertex.o

# target to build an object file
Vertex.cpp.o:
	$(MAKE) -f CMakeFiles/Vertex.dir/build.make CMakeFiles/Vertex.dir/Vertex.cpp.o
.PHONY : Vertex.cpp.o

Vertex.i: Vertex.cpp.i

.PHONY : Vertex.i

# target to preprocess a source file
Vertex.cpp.i:
	$(MAKE) -f CMakeFiles/Vertex.dir/build.make CMakeFiles/Vertex.dir/Vertex.cpp.i
.PHONY : Vertex.cpp.i

Vertex.s: Vertex.cpp.s

.PHONY : Vertex.s

# target to generate assembly for a file
Vertex.cpp.s:
	$(MAKE) -f CMakeFiles/Vertex.dir/build.make CMakeFiles/Vertex.dir/Vertex.cpp.s
.PHONY : Vertex.cpp.s

predicates.o: predicates.c.o

.PHONY : predicates.o

# target to build an object file
predicates.c.o:
	$(MAKE) -f CMakeFiles/predicates.dir/build.make CMakeFiles/predicates.dir/predicates.c.o
.PHONY : predicates.c.o

predicates.i: predicates.c.i

.PHONY : predicates.i

# target to preprocess a source file
predicates.c.i:
	$(MAKE) -f CMakeFiles/predicates.dir/build.make CMakeFiles/predicates.dir/predicates.c.i
.PHONY : predicates.c.i

predicates.s: predicates.c.s

.PHONY : predicates.s

# target to generate assembly for a file
predicates.c.s:
	$(MAKE) -f CMakeFiles/predicates.dir/build.make CMakeFiles/predicates.dir/predicates.c.s
.PHONY : predicates.c.s

triangulate.o: triangulate.cpp.o

.PHONY : triangulate.o

# target to build an object file
triangulate.cpp.o:
	$(MAKE) -f CMakeFiles/triangulate.dir/build.make CMakeFiles/triangulate.dir/triangulate.cpp.o
.PHONY : triangulate.cpp.o

triangulate.i: triangulate.cpp.i

.PHONY : triangulate.i

# target to preprocess a source file
triangulate.cpp.i:
	$(MAKE) -f CMakeFiles/triangulate.dir/build.make CMakeFiles/triangulate.dir/triangulate.cpp.i
.PHONY : triangulate.cpp.i

triangulate.s: triangulate.cpp.s

.PHONY : triangulate.s

# target to generate assembly for a file
triangulate.cpp.s:
	$(MAKE) -f CMakeFiles/triangulate.dir/build.make CMakeFiles/triangulate.dir/triangulate.cpp.s
.PHONY : triangulate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Vertex"
	@echo "... Delaunay_triangulation"
	@echo "... Face"
	@echo "... Point"
	@echo "... triangulate"
	@echo "... Point_with_info"
	@echo "... HODT"
	@echo "... Triangulation"
	@echo "... Face_circulator"
	@echo "... predicates"
	@echo "... Delaunay_triangulation.o"
	@echo "... Delaunay_triangulation.i"
	@echo "... Delaunay_triangulation.s"
	@echo "... Face.o"
	@echo "... Face.i"
	@echo "... Face.s"
	@echo "... Face_circulator.o"
	@echo "... Face_circulator.i"
	@echo "... Face_circulator.s"
	@echo "... HODT.o"
	@echo "... HODT.i"
	@echo "... HODT.s"
	@echo "... Point.o"
	@echo "... Point.i"
	@echo "... Point.s"
	@echo "... Point_with_info.o"
	@echo "... Point_with_info.i"
	@echo "... Point_with_info.s"
	@echo "... Triangulation.o"
	@echo "... Triangulation.i"
	@echo "... Triangulation.s"
	@echo "... Vertex.o"
	@echo "... Vertex.i"
	@echo "... Vertex.s"
	@echo "... predicates.o"
	@echo "... predicates.i"
	@echo "... predicates.s"
	@echo "... triangulate.o"
	@echo "... triangulate.i"
	@echo "... triangulate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

